[project]
name = "smrs"
version = "0.1.0"
description = "Sparse Modeling Representative Selection"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "argparse>=1.4.0",
    "clip @ git+https://github.com/openai/CLIP.git",
    "numpy>=1.24.0",
    "torch>=2.0.0",
    "torchvision>=0.15.0",
    "tqdm>=4.60.0",
    "omegaconf>=2.3.0",
    "pytest>=8.4.2",
]

[project.scripts]
smrs-run = "scripts.main:main"
smrs-dataset = "scripts.run_smrs_on_dataset:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true
